services:
    - type: web
      name: bariosk
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: python app.py
      envVars:
          - key: PYTHON_VERSION
            value: 3.9.0
      disk:
          name: data
          mountPath: /data
          sizeGB: 1
