services:
    - type: web
      name: bariosk
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: python app.py
      envVars:
          - key: PYTHON_VERSION
            value: 3.9.0
          - key: RENDER
            value: "true"
      disk:
          name: data
          mountPath: /opt/render/project/src
          sizeGB: 1
